#!/usr/bin/env ruby
#^syntax detection
#
# after adding cookbooks
#   librarian-chef install

site 'http://community.opscode.com/api/v1'

cookbook 'apache2'
cookbook 'users'
cookbook 'git'
cookbook 'apt'
cookbook 'couchdb'
cookbook 'sudo'
cookbook 'emacs'
cookbook 'maven'

cookbook 'java',          :git => 'https://github.com/opscode-cookbooks/java'
cookbook 'nodejs',        :git => 'https://github.com/mdxp/nodejs-cookbook'
cookbook 'npm',           :git => 'https://github.com/balbeko/chef-npm/'
cookbook 'authbind',      :git => 'https://github.com/realityforge-cookbooks/authbind'

# http://fnichol.github.com/chef-rvm/
cookbook 'rvm',           :git => 'git://github.com/fnichol/chef-rvm.git', :ref => 'v0.9.0'

# https://github.com/fnichol/chef-rvm_passenger
cookbook 'rvm_passenger', :git => 'git://github.com/fnichol/chef-rvm_passenger.git', :ref => 'v0.8.0'
