#!/usr/bin/env ruby
#^syntax detection
#
# after adding cookbooks
#   librarian-chef install

site 'http://community.opscode.com/api/v1'

cookbook 'apache2'
cookbook 'users'
cookbook 'git'
cookbook 'apt'
cookbook 'couchdb'
cookbook 'sudo'
cookbook 'emacs'
cookbook 'maven'
cookbook 'chef-solo-search'

cookbook 'java',          :git => 'git://github.com/opscode-cookbooks/java.git'
cookbook 'nodejs',        :git => 'git://github.com/mdxp/nodejs-cookbook.git'
cookbook 'npm',           :git => 'git://github.com/balbeko/chef-npm.git'
cookbook 'authbind',      :git => 'git://github.com/realityforge/chef-authbind.git'
cookbook 'zip',           :git => 'git://github.com/phlipper/chef-zip.git'

# https://github.com/opscode-cookbooks/ark/pull/8
cookbook 'ark',           :git => 'git://github.com/opscode-cookbooks/ark.git'

# http://fnichol.github.com/chef-rvm/
cookbook 'rvm',           :git => 'git://github.com/fnichol/chef-rvm.git'

# https://github.com/fnichol/chef-rvm_passenger
cookbook 'rvm_passenger', :git => 'git://github.com/fnichol/chef-rvm_passenger.git', :ref => 'v0.8.0'

# https://github.com/customink-webops/phantomjs
cookbook 'phantomjs',     :git => 'git://github.com/customink-webops/phantomjs.git'

