#!/usr/bin/env ruby
#^syntax detection
#
# after adding cookbooks
#   librarian-chef install

site 'http://community.opscode.com/api/v1'
# this is how to set a default source for git
# git 'https://github.com/concord-consortium/chef-repo', :path => 'cookbooks'

cookbook 'apache2'
cookbook 'users'
cookbook 'git'
cookbook 'apt'
cookbook 'couchdb'
cookbook 'sudo'
cookbook 'emacs'
cookbook 'java'
cookbook 'maven'

cookbook 'nodejs',
    :git => 'https://github.com/mdxp/nodejs-cookbook'
cookbook 'npm',
    :git => 'https://github.com/balbeko/chef-npm/'
cookbook 'authbind',
    :git => 'https://github.com/realityforge-cookbooks/authbind'

cookbook 'rvm',
    :git => 'git://github.com/fnichol/chef-rvm.git', :ref => 'v0.9.0'
    # http://fnichol.github.com/chef-rvm/

cookbook 'rvm_passenger',
    :git => 'git://github.com/fnichol/chef-rvm_passenger.git', :ref => 'v0.8.0'
    # https://github.com/fnichol/chef-rvm_passenger

# example cookbook descriptions
# cookbook 'apache2', '>= 1.0.0'
#
# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'
#
# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
