default[:rails][:min_instances] = 1
default[:lara][:db_database] = "portal"
default[:lara][:db_pool] = 5
default[:lara][:rds_domain] = "cc-us-east-1"
default[:lara][:site_name] = "Lightweight Activity Runtime and Authoring"
default[:lara][:site_url] = "http://localhost:3000"
default[:lara][:email] = "authoring-help@concord.org"
default[:lara][:static_assets] = true
default[:lara][:google_analytics_account] = "UA-6899787-23"
